### PR TITLE
Allows StataPush to run a do file so that you'll receive a notification if the do file runs into an error.

### PR DESCRIPTION
**Pull request by vikjam**
Adds the ability to run a do file, which will you to receive a notification if there's an error in your code.

``` stata
* Install fork
net install statapush, from("https://raw.github.com/vikjam/statapush/master/") replace

* Create an example do file that has an error
file open example using "example-do.do", write
file write example "sysuse auto.dta" _n "regressx mpg price" _n
file close example

* Run statapush
statapush using "example-do.do", token(<INSERT API TOKEN>) userid(<INSERT USER KEY>) message(<INSERT MESSAGE>)
```

### CODE REVIEW

**Comment by wschpero** [comment]
Hi,

Would you prefer to submit separate pull requests for the error handling function and the storing preferences / pushbullet contributions? Or just one with everything?

Best,
Will

**Comment by vikjam** [comment]
I just put everything together now!

**Comment by wschpero** [comment]
Great - thanks! I'll merge, take a quick look, and then submit an update to SSC in the next day or two!.

**Comment by wschpero** [comment]
Hi,

I just submitted a few additional changes - mostly to documentation. I think it's ready to submit to SSC. I'll plan to email it in tomorrow morning. Please let me know before then if you'd like to be included as a named author.

Thanks again!

Best,
Will

**Comment by vikjam** [comment]
Being included as an author sounds good! Thanks for offering it!

**Comment by wschpero** [comment]
Great! Can you send me your name and email address?

Thx!

**Pull request merged**
